[feature]-[12]-[semver:minor]- Create Survey sayfasının tasarımı kısmı tamamlandı.
bimser-intern/surveysaurus-ui pull request #13
Opened 2022-08-16 08:34 UTC by felataslan

#12 
Create Survey sayfasının tasarımı kısmı tamamlandı.

2022-08-16 10:18 UTC, rahimeT approved these changes

2022-08-16 14:42 UTC, omerhamsi approved these changes

2022-08-17 06:33 UTC, otipirdamaz requested changes

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/style/CreateSurvey.css.map
> +{"version":3,"sources":["CreateSurvey.scss","CreateSurvey.css"],"names":[],"mappings":"AAAA;EACI,yBAAA;EACA,0BAAA;ACCJ;;ADEA;EACI,WAAA;EACA,aAAA;EACA,aAAA;EACA,uBAAA;EACA,mBAAA;EACA,iBAAA;ACCJ;ADCI;E
map dosyalarının git de saklanmasına gerek yok. gitignore dosyasına ekleyebilirsiniz.

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/screens/CreateSurvey.js
> +              <div onClick={addOption} style={{ display: "flex", flexDirection: "row", cursor: "pointer" }} className='addOption'>
sabit yazılan inline style ları css'e yazmak daha performanslı olur. Style olarak yazılması gerekiyorsa değişmiyorsa const olarak tanımlamak daha iyi olur. Tüm projeye uygulamak gerekli bu yaklaşımı başka sayfalarda da var.

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/components/surveycreate.js
> +function surveyCreate(){
isimlendirme standartına uygun olmayan dosya adı

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/screens/CreateSurvey.js
> +          <li><Link to={"/"} className='navItem'>Home</Link>
buradaki home, about, sign up login vs. tasarımı Menu component'inden farklı mı? Menu component'inin kullanılması gerekiyor sanki

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/screens/CreateSurvey.js
> +      <div className='createSurveyContainer'>
bu method içeriği fazla uzun mantıksal bölümlere ayırabilirsin daha anlaşılır ve temiz görünür

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/style/CreateSurvey.css
> +.borderBottom {
css dosyası yerine scss dosyasını kullanmalısınız. Bu şekilde 2 ayrı css dosyası var olmuş oluyor. Bu dosyadaki içeriği scss e taşıdığınızda css'lerinizin içinde optimize etmeniz gereken yerleri de düzenlemelisiniz.

2022-08-17 06:33 UTC, otipirdamaz commented on survey-app/src/style/CreateSurvey.css
> +.borderBottom {
css dosyası yerine scss dosyasını kullanmalısınız. Bu şekilde 2 ayrı css dosyası var olmuş oluyor. Bu dosyadaki içeriği scss e taşıdığınızda css'lerinizin içinde optimize etmeniz gereken yerleri de düzenlemelisiniz.

2022-08-17 08:20 UTC, otipirdamaz requested changes

2022-08-17 08:20 UTC, otipirdamaz commented on survey-app/.gitignore
> +surveysaurus-ui/survey-app/style/CreateSurvey.css.map
dosyaları bu şekilde değil de src/*.map gibi eklerseniz daha temiz olur

2022-08-17 08:20 UTC, otipirdamaz commented on survey-app/public/index.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.min.js"></script>
react'ın js dosyasını eklemeye ihtiyacınız var mıydı ondan emin olamadım zaten bundle sırasında paketleniyor olması lazım

2022-08-17 08:20 UTC, otipirdamaz commented on survey-app/src/components/surveyCard.js
>  function surveyCard() {
Component ismi ve dosya isimlendirmesi uygun değil SurveyCard şeklinde olmalı

2022-08-17 08:20 UTC, otipirdamaz commented on survey-app/src/screens/CreateSurvey.js
> +const data ={ backgroundColor: "rgba(240, 184, 13, 0.38)", marginBottom: "50px", border: "1px solid rgba(240, 184, 13, 0.38)", borderRadius: "10px" };
değişken isimlendirmesi uygun değil. Bu style lar öncelikle css e dönüştürülmeli inline kullanmak zorunlu ise const yapılmalı ve kullanıldığı yere göre değişken isimlendirmesine dikkat edilmeli

2022-08-17 09:46 UTC, otipirdamaz requested changes

2022-08-17 09:46 UTC, otipirdamaz commented on survey-app/.gitignore
> +surveysaurus-ui/survey-app/src/style/*.map
yanlış bir tanımlama olmuş doğru tanımlamayı yaptığında map dosyasının change listesinden çıktığını görmen lazım

2022-08-17 09:46 UTC, otipirdamaz commented on survey-app/src/components/surveyCard.js
> +function SurveyCard() {
Dosya ismi küçük harfli kalmış

2022-08-17 14:17 UTC, eraydnci approved these changes

2022-08-17 14:47 UTC, otipirdamaz approved these changes

2022-08-17 14:55 UTC, om3rd approved these changes

2022-08-17 14:56 UTC, merged