[feature]-[15]-[semver:minor]- Validation, Log in, Sign up kontrolleri
bimser-intern/surveysaurus-ui pull request #16
Opened 2022-08-16 14:40 UTC by omerhamsi

-Validation uyarı mesajları düzenlendi.
-Log in, sign up kontolleri ve yönlendirmeleri yapıldı.
-Token ve auth bilgileri local strorage eklendi.
-Kullanıcı sayfası menüsü dinamik hale getirildi. 
#15

2022-08-16 21:41 UTC, felataslan submitted a review, later dismissed

2022-08-17 14:55 UTC, om3rd submitted a review, later dismissed

2022-08-17 17:23 UTC, felataslan approved these changes

2022-08-18 08:00 UTC, otipirdamaz requested changes

2022-08-18 08:00 UTC, otipirdamaz commented on survey-app/src/screens/Login.js
> +          alert("kullanıcı adı veya şifre yanlış");
her yer İngilizce burası Türkçe olmuş

2022-08-18 08:00 UTC, otipirdamaz commented on survey-app/src/screens/SignUp.js
> +                    alert("kullanıcı başarıyla kayıt edildi")
dil

2022-08-18 09:38 UTC, otipirdamaz approved these changes

2022-08-18 09:39 UTC, felataslan approved these changes

2022-08-18 09:40 UTC, eraydnci approved these changes

2022-08-18 09:42 UTC, muhammetduzenli approved these changes

2022-08-18 09:42 UTC, merged